version: '3.9'

services:
  nginx:
    depends_on: [redis]
    ports: [8080:8080]
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - .:/lua/
    build:
      context: .

  test:
    command: busted
    volumes:
      - .:/lua/
    working_dir: /lua
    build:
      context: .
      dockerfile: Dockerfile.test

  lint:
    command: luacheck -q .
    volumes:
      - .:/lua/
    working_dir: /lua
    build:
      context: .
      dockerfile: Dockerfile.test

  redis:
    image: grokzen/redis-cluster:latest
    expose: [ 7000 ]